global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "Prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'Java Services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['spring-boot-trace-metric-example:8080']