version: "3.9"
services:

  prometheus:
    image: prom/prometheus:v2.47.2
    hostname: prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - volume:/prometheus
    ports:
      - 9090:9090

volumes:
  volume:

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}